# Generated by Django 6.1.1 on 2026-09-19 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('infraestructura', '0001_initial'),
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_incidente', models.CharField(blank=True, max_length=50, null=True)),
                ('prioridad', models.ForeignKey(blank=True, db_column='prioridad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='catalogos.prioridad')),
                ('tipo', models.ForeignKey(blank=True, db_column='tipo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='catalogos.tipoincidente')),
            ],
            options={
                'db_table': 'incidente',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(blank=True, max_length=255, null=True)),
                ('destino', models.CharField(blank=True, max_length=255, null=True)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tiempo_estimado', models.IntegerField(blank=True, null=True)),
                ('tiempo_real', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('ambulancia', models.ForeignKey(blank=True, db_column='ambulancia_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='infraestructura.ambulancia')),
                ('centro_salud_destino', models.ForeignKey(blank=True, db_column='centro_salud_destino_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='infraestructura.centrosalud')),
                ('conductor', models.ForeignKey(blank=True, db_column='conductor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='personal.datosconductor')),
                ('incidente', models.ForeignKey(blank=True, db_column='incidente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='despacho.incidente')),
            ],
            options={
                'db_table': 'rutas',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_origen', models.CharField(blank=True, max_length=255, null=True)),
                ('ambulancia', models.ForeignKey(blank=True, db_column='ambulancia_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='infraestructura.ambulancia')),
                ('centro_salud_destino', models.ForeignKey(blank=True, db_column='centro_salud_destino_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='infraestructura.centrosalud')),
                ('conductor', models.ForeignKey(blank=True, db_column='conductor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='personal.datosconductor')),
                ('estado', models.ForeignKey(blank=True, db_column='estado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='catalogos.estadosolicitud')),
                ('ruta', models.ForeignKey(blank=True, db_column='ruta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='despacho.ruta')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.AddField(
            model_name='incidente',
            name='solicitud',
            field=models.ForeignKey(blank=True, db_column='solicitud_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='despacho.solicitud'),
        ),
        migrations.CreateModel(
            name='UsuarioIncidente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incidente', models.ForeignKey(db_column='incidente_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asociados', to='despacho.incidente')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_asociados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_incidente',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'incidente'), name='unique_usuario_incidente')],
            },
        ),
    ]
