# Generated by Django 6.1.1 on 2026-09-19 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroSalud',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_centro', models.ForeignKey(blank=True, db_column='tipo_centro_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_salud', to='catalogos.tipocentro')),
            ],
            options={
                'db_table': 'centros_salud',
            },
        ),
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('id_ambulancia', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20)),
                ('estado', models.ForeignKey(blank=True, db_column='estado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulancias', to='catalogos.estadoambulancia')),
                ('tipo', models.ForeignKey(blank=True, db_column='tipo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulancias', to='catalogos.tipoambulancia')),
                ('centro_salud', models.ForeignKey(blank=True, db_column='centro_salud_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulancias', to='infraestructura.centrosalud')),
            ],
            options={
                'db_table': 'ambulancias',
            },
        ),
    ]
