# Generated by Django 6.1.1 on 2026-09-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Personal', 'Personal'), ('Operador', 'Operador'), ('Administrador', 'Administrador')], max_length=50),
        ),
    ]
