# Generated by Django 6.1.1 on 2026-09-19 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestructura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosConductor',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('licencia', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria_licencia', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('centro_salud', models.ForeignKey(blank=True, db_column='centro_salud_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductores', to='infraestructura.centrosalud')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_conductor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'datos_conductor',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estado_turno', models.CharField(blank=True, max_length=50, null=True)),
                ('ambulancia', models.ForeignKey(blank=True, db_column='ambulancia_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='infraestructura.ambulancia')),
                ('conductor', models.ForeignKey(blank=True, db_column='conductor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='personal.datosconductor')),
            ],
            options={
                'db_table': 'turnos',
            },
        ),
    ]
