# Generated by Django 6.1.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('usuarios', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('atendida_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_password', to='usuarios.usuario')),
            ],
            options={'db_table': 'solicitudes_cambio_password', 'ordering': ['-creada_en']},
        ),
    ]
